package javaapplication9;
// Generated Aug 10, 2017 6:10:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Ficha generated by hbm2java
 */
public class Ficha  implements java.io.Serializable {


     private long dni;
     private String nombre;
     private String apellido;
     private Date fechanac;
     private Date fechaingreso;
     private String categoria;
     private String localidad;
     private String domicilio;
     private BigDecimal telefono;
     private String estadocivil;
     private long codigopostal;

    public Ficha() {
    }

	
    public Ficha(long dni) {
        this.dni = dni;
    }
    public Ficha(long dni, String nombre, String apellido, Date fechanac, Date fechaingreso, String categoria, String localidad, String domicilio, BigDecimal telefono, String estadocivil, Long codigopostal) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechanac = fechanac;
       this.fechaingreso = fechaingreso;
       this.categoria = categoria;
       this.localidad = localidad;
       this.domicilio = domicilio;
       this.telefono = telefono;
       this.estadocivil = estadocivil;
       this.codigopostal = codigopostal;
    }
   
    public long getDni() {
        return this.dni;
    }
    
    public void setDni(long dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public String getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(String estadocivil) {
        this.estadocivil = estadocivil;
    }
    public Long getCodigopostal() {
        return this.codigopostal;
    }
    
    public void setCodigopostal(Long codigopostal) {
        this.codigopostal = codigopostal;
    }




}


