package javaapplication9;
// Generated Aug 10, 2017 6:10:05 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private BigDecimal codigoprod;
     private String nombreprod;
     private String lineaprod;
     private Boolean esneto;
     private Integer cantidad;
     private BigDecimal precioventapublico;

    public Producto() {
    }

	
    public Producto(BigDecimal codigoprod) {
        this.codigoprod = codigoprod;
    }
    public Producto(BigDecimal codigoprod, String nombreprod, String lineaprod, Boolean esneto, Integer cantidad, BigDecimal precioventapublico) {
       this.codigoprod = codigoprod;
       this.nombreprod = nombreprod;
       this.lineaprod = lineaprod;
       this.esneto = esneto;
       this.cantidad = cantidad;
       this.precioventapublico = precioventapublico;
    }
   
    public BigDecimal getCodigoprod() {
        return this.codigoprod;
    }
    
    public void setCodigoprod(BigDecimal codigoprod) {
        this.codigoprod = codigoprod;
    }
    public String getNombreprod() {
        return this.nombreprod;
    }
    
    public void setNombreprod(String nombreprod) {
        this.nombreprod = nombreprod;
    }
    public String getLineaprod() {
        return this.lineaprod;
    }
    
    public void setLineaprod(String lineaprod) {
        this.lineaprod = lineaprod;
    }
    public Boolean getEsneto() {
        return this.esneto;
    }
    
    public void setEsneto(Boolean esneto) {
        this.esneto = esneto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioventapublico() {
        return this.precioventapublico;
    }
    
    public void setPrecioventapublico(BigDecimal precioventapublico) {
        this.precioventapublico = precioventapublico;
    }




}


