package javaapplication9;
// Generated Aug 10, 2017 6:10:05 PM by Hibernate Tools 4.3.1



/**
 * VentaId generated by hbm2java
 */
public class VentaId  implements java.io.Serializable {


     private long codigoproducto;
     private long dni;

    public VentaId() {
    }

    public VentaId(long codigoproducto, long dni) {
       this.codigoproducto = codigoproducto;
       this.dni = dni;
    }
   
    public long getCodigoproducto() {
        return this.codigoproducto;
    }
    
    public void setCodigoproducto(Long codigoproducto) {
        this.codigoproducto = codigoproducto;
    }
    public long getDni() {
        return this.dni;
    }
    
    public void setDni(Long dni) {
        this.dni = dni;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentaId) ) return false;
		 VentaId castOther = ( VentaId ) other; 
         
		 return (this.getCodigoproducto()==castOther.getCodigoproducto())
 && (this.getDni()==castOther.getDni());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCodigoproducto();
         result = 37 * result + (int) this.getDni();
         return result;
   }   


}


