package javaapplication9;
// Generated 10/10/2017 17:36:14 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private VentaId id;
     private Ficha ficha;
     private Date fecha;
     private Long cantidad;

    public Venta() {
    }

	
    public Venta(VentaId id, Ficha ficha, Date fecha) {
        this.id = id;
        this.ficha = ficha;
        this.fecha = fecha;
    }
    public Venta(VentaId id, Ficha ficha, Date fecha, Long cantidad) {
       this.id = id;
       this.ficha = ficha;
       this.fecha = fecha;
       this.cantidad = cantidad;
    }
   
    public VentaId getId() {
        return this.id;
    }
    
    public void setId(VentaId id) {
        this.id = id;
    }
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Long cantidad) {
        this.cantidad = cantidad;
    }




}


